"""Turn build/models/*.json into src/shared/Config/ModelLibrary.luau.

    python3 tools/models/manifest.py

The library is generated (do not edit by hand); uploaded asset ids live
separately in ModelAssets.luau so rebuilding models never loses them."""

import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "build", "models")
OUT = os.path.join(ROOT, "src", "shared", "Config", "ModelLibrary.luau")


def num(x):
    return f"{x:g}"


def vec(v):
    return "Vector3.new(" + ", ".join(num(x) for x in v) + ")"


lines = [
    "--!strict",
    "-- GENERATED by tools/models/manifest.py from the Blender models in",
    "-- tools/models. Do not edit: change the model script and rebuild.",
    "--",
    "-- Per model: its proportions (height 1) and, per part role, the colour,",
    "-- material, tint mode (coloured by the enemy) and bounding box (centre",
    "-- and extent, for orienting the imported mesh).",
    "",
    "export type Part = { Color: Color3, Material: Enum.Material, Tint: string?, Center: Vector3, Extent: Vector3 }",
    "export type Model = { Size: Vector3, Parts: { [string]: Part } }",
    "",
    "local ModelLibrary: { [string]: Model } = {",
]
for name in sorted(f[:-5] for f in os.listdir(SRC) if f.endswith(".json")):
    m = json.load(open(os.path.join(SRC, name + ".json")))
    lines.append(f"\t{name} = {{")
    lines.append(f"\t\tSize = {vec(m['Size'])},")
    lines.append("\t\tParts = {")
    for role in sorted(m["Parts"]):
        p = m["Parts"][role]
        tint = f', Tint = "{p["Tint"]}"' if "Tint" in p else ""
        color = "Color3.fromRGB(" + ", ".join(str(c) for c in p["Color"]) + ")"
        lines.append(
            f"\t\t\t{role} = {{ Color = {color}, Material = Enum.Material.{p['Material']}{tint}, Center = {vec(p['Center'])}, Extent = {vec(p['Extent'])} }},"
        )
    lines.append("\t\t},")
    lines.append("\t},")
lines += ["}", "", "return ModelLibrary", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}")
